### ISSUE TITLE
Reference material / Previous attempts

### ISSUE THREAD

**Issue by BlackPhlox** [TheBevyFlock/bevybot#1]
Hi there!

Looking forward to what this could mean for developing on and with Bevy!

I've previously tried to create a discord bot but famously ran out of time to work on the project.
The project was mostly focused on parsing discord messages that contained references to the bevy repositories, to which the bevy bot responded with some info about that code and showed code snippets.

The code is not that important but there were some nice discussions about ideas etc. in the issues of the repo that I would recommend you take a look at.

https://github.com/BlackPhlox/bevy-bot

Good luck! 🚀

**Comment by BD103** [comment]
Hey, thank you so much for stopping by! This is going to be a Github bot, not a Discord bot, so it has slightly different requirements. Either way, I appreciate that you managed to find this! I'll take a look at your code and see if there is anything I can ~~steal~~ _permanently borrow_.

Cheers :)
